// Frontend-Angular/src/app/components/modal/modal.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideX } from '@lucide/angular';

@Component({
  selector: 'app-modal',
  standalone: true,
  imports: [CommonModule, LucideX],
  template: `
    <div *ngIf="isOpen" class="fixed inset-0 z-50 flex items-center justify-center p-4">
      <!-- Backdrop -->
      <div (click)="onClose.emit()" class="fixed inset-0 bg-black/60 backdrop-blur-sm"></div>

      <!-- Modal Panel -->
      <div class="relative w-full max-w-lg glass-surface bg-white/90 dark:bg-zinc-900/90 border border-zinc-950/10 dark:border-white/15 rounded-3xl p-6 shadow-2xl text-left z-10">
        <!-- Close Button -->
        <button
          (click)="onClose.emit()"
          class="absolute top-4 right-4 p-1.5 rounded-full border border-zinc-950/10 dark:border-white/10 text-zinc-400 hover:text-zinc-950 dark:hover:text-white transition-colors flex items-center justify-center"
          aria-label="Kapat"
        >
          <svg lucideX class="w-4 h-4"></svg>
        </button>

        <!-- Header -->
        <h3 *ngIf="title" class="text-xl font-bold tracking-tight text-zinc-900 dark:text-white mb-4 pr-8">{{ title }}</h3>

        <!-- Content -->
        <div class="max-h-[75vh] overflow-y-auto pr-1">
          <ng-content></ng-content>
        </div>
      </div>
    </div>
  `
})
export class ModalComponent {
  @Input() isOpen = false;
  @Input() title = '';
  @Output() onClose = new EventEmitter<void>();
}

// Frontend - React/src/components/Modal.tsx
import React, { useEffect, ReactNode } from 'react';
import { X } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
  title?: string;
  children: ReactNode;
}

export const Modal: React.FC<ModalProps> = ({ isOpen, onClose, title, children }) => {
  // Prevent scrolling when modal is open
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = 'unset';
    }
    return () => {
      document.body.style.overflow = 'unset';
    };
  }, [isOpen]);

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-black/60 backdrop-blur-sm"
          />

          {/* Modal Panel */}
          <motion.div
            initial={{ scale: 0.95, opacity: 0, y: 15 }}
            animate={{ scale: 1, opacity: 1, y: 0 }}
            exit={{ scale: 0.95, opacity: 0, y: 15 }}
            transition={{ duration: 0.25, ease: 'easeOut' }}
            className="relative w-full max-w-lg glass-surface bg-white/90 dark:bg-zinc-900/90 border border-zinc-950/10 dark:border-white/15 rounded-3xl p-6 shadow-2xl text-left z-10"
          >
            {/* Close Button */}
            <button
              onClick={onClose}
              className="absolute top-4 right-4 p-1.5 rounded-full border border-zinc-950/10 dark:border-white/10 text-zinc-400 hover:text-zinc-950 dark:hover:text-white transition-colors"
              aria-label="Kapat"
            >
              <X className="w-4 h-4" />
            </button>

            {/* Header */}
            {title && (
              <h3 className="text-xl font-bold tracking-tight text-zinc-900 dark:text-white mb-4 pr-8">
                {title}
              </h3>
            )}

            {/* Content */}
            <div className="max-h-[75vh] overflow-y-auto pr-1">
              {children}
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};
