// frontend/src/app/pages/account/account.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { CustomerService } from '../../services/customer.service';
import { SellerService } from '../../services/seller.service';
import { ToastService } from '../../services/toast.service';
import { CommentService } from '../../services/comment.service';
import { CommentDto } from '../../models/api.types';
import { InputComponent } from '../../components/input/input.component';
import { ButtonComponent } from '../../components/button/button.component';
import { PaginationComponent } from '../../components/pagination/pagination.component';
import { LucideUser, LucideLock, LucideMessageSquare, LucideStore, LucideAlertCircle, LucideShieldAlert, LucideFileText, LucideExternalLink, LucideTrash2, LucideCalendar, LucideStar } from '@lucide/angular';

@Component({
  selector: 'app-account',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    RouterLink,
    InputComponent,
    ButtonComponent,
    PaginationComponent,
    LucideUser,
    LucideLock,
    LucideMessageSquare,
    LucideStore,
    LucideAlertCircle,
    LucideShieldAlert,
    LucideFileText,
    LucideExternalLink,
    LucideTrash2,
    LucideCalendar,
    LucideStar
  ],
  template: `
    <div class="max-w-4xl mx-auto px-6 py-10 space-y-8 text-left">
      
      <!-- Header -->
      <div class="border-b border-zinc-950/5 dark:border-white/5 pb-6">
        <h1 class="text-4xl font-extrabold tracking-tight text-zinc-950 dark:text-white uppercase leading-none">
          Hesabım
        </h1>
        <p class="text-sm text-zinc-500 dark:text-zinc-400 mt-1.5">
          Kişisel bilgilerinizi, şifrenizi yönetin ve mağaza başvurularınızı inceleyin.
        </p>
      </div>

      <!-- Tabs Layout -->
      <div class="grid grid-cols-1 md:grid-cols-4 gap-8">
        
        <!-- Sidebar Navigation -->
        <nav class="md:col-span-1 flex flex-col gap-2">
          <button
            (click)="setActiveTab('profile')"
            [class]="'flex items-center gap-2.5 px-4 py-3 rounded-xl text-sm font-semibold text-left transition-all ' + 
              (activeTab === 'profile'
                ? 'bg-zinc-950 text-white dark:bg-white dark:text-zinc-950 shadow-md'
                : 'text-zinc-600 dark:text-zinc-400 hover:bg-zinc-950/5 dark:hover:bg-white/5')"
          >
            <svg lucideUser class="w-4 h-4"></svg> Profilim
          </button>
          
          <button
            (click)="setActiveTab('password')"
            [class]="'flex items-center gap-2.5 px-4 py-3 rounded-xl text-sm font-semibold text-left transition-all ' + 
              (activeTab === 'password'
                ? 'bg-zinc-950 text-white dark:bg-white dark:text-zinc-950 shadow-md'
                : 'text-zinc-600 dark:text-zinc-400 hover:bg-zinc-950/5 dark:hover:bg-white/5')"
          >
            <svg lucideLock class="w-4 h-4"></svg> Şifre Değiştir
          </button>

          <button
            (click)="setActiveTab('comments')"
            [class]="'flex items-center gap-2.5 px-4 py-3 rounded-xl text-sm font-semibold text-left transition-all ' + 
              (activeTab === 'comments'
                ? 'bg-zinc-950 text-white dark:bg-white dark:text-zinc-950 shadow-md'
                : 'text-zinc-600 dark:text-zinc-400 hover:bg-zinc-950/5 dark:hover:bg-white/5')"
          >
            <svg lucideMessageSquare class="w-4 h-4"></svg> Değerlendirmelerim
          </button>
          
          <button
            (click)="setActiveTab('seller')"
            [class]="'flex items-center gap-2.5 px-4 py-3 rounded-xl text-sm font-semibold text-left transition-all ' + 
              (activeTab === 'seller'
                ? 'bg-zinc-950 text-white dark:bg-white dark:text-zinc-950 shadow-md'
                : 'text-zinc-600 dark:text-zinc-400 hover:bg-zinc-950/5 dark:hover:bg-white/5')"
          >
            <svg lucideStore class="w-4 h-4"></svg> Satıcı Paneli / Başvuru
          </button>
        </nav>

        <!-- Tab Contents -->
        <main class="md:col-span-3 glass-surface bg-zinc-950/[0.01] dark:bg-white/5 border border-zinc-950/5 dark:border-white/10 p-8 rounded-3xl">
          
          <!-- Tab 1: Profilim -->
          <div *ngIf="activeTab === 'profile'">
            <form (ngSubmit)="onUpdateProfile()" class="space-y-6">
              <h3 class="text-lg font-bold text-zinc-950 dark:text-white uppercase tracking-wide border-b border-zinc-950/5 dark:border-white/5 pb-2.5 flex items-center gap-2">
                <svg lucideUser class="w-5 h-5 text-zinc-400"></svg> Profil Bilgileri
              </h3>

              <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <app-input
                  label="Ad"
                  placeholder="Adınız"
                  [(ngModel)]="profileData.firstName"
                  name="firstName"
                  [error]="profileErrors.firstName"
                ></app-input>
                <app-input
                  label="Soyad"
                  placeholder="Soyadınız"
                  [(ngModel)]="profileData.lastName"
                  name="lastName"
                  [error]="profileErrors.lastName"
                ></app-input>
              </div>

              <div class="flex flex-col gap-3">
                <app-input
                  label="E-posta Adresi (Değiştirilemez)"
                  type="email"
                  [disabled]="true"
                  [(ngModel)]="profileEmail"
                  name="email"
                  className="opacity-60 cursor-not-allowed bg-zinc-950/5 dark:bg-white/5"
                ></app-input>

                <app-input
                  label="Telefon Numarası"
                  placeholder="5xxxxxxxxx"
                  [(ngModel)]="profileData.phoneNumber"
                  name="phoneNumber"
                  [error]="profileErrors.phoneNumber"
                ></app-input>
              </div>

              <div class="pt-4">
                <app-button type="submit" variant="primary" [disabled]="isLoading">
                  {{ isLoading ? 'Güncelleniyor...' : 'Profilimi Güncelle' }}
                </app-button>
              </div>
            </form>
          </div>

          <!-- Tab 2: Şifre Değiştir -->
          <div *ngIf="activeTab === 'password'">
            <form (ngSubmit)="onChangePassword()" class="space-y-6">
              <h3 class="text-lg font-bold text-zinc-950 dark:text-white uppercase tracking-wide border-b border-zinc-950/5 dark:border-white/5 pb-2.5 flex items-center gap-2">
                <svg lucideLock class="w-5 h-5 text-zinc-400"></svg> Güvenlik & Şifre
              </h3>

              <app-input
                label="Mevcut Şifre"
                type="password"
                placeholder="••••••••"
                [(ngModel)]="passwordData.currentPassword"
                name="currentPassword"
                [error]="passwordErrors.currentPassword"
              ></app-input>

              <app-input
                label="Yeni Şifre"
                type="password"
                placeholder="••••••••"
                [(ngModel)]="passwordData.newPassword"
                name="newPassword"
                [error]="passwordErrors.newPassword"
              ></app-input>

              <app-input
                label="Yeni Şifre Tekrar"
                type="password"
                placeholder="••••••••"
                [(ngModel)]="passwordData.confirmNewPassword"
                name="confirmNewPassword"
                [error]="passwordErrors.confirmNewPassword"
              ></app-input>

              <div class="pt-4">
                <app-button type="submit" variant="primary" [disabled]="isLoading">
                  {{ isLoading ? 'Değiştiriliyor...' : 'Şifreyi Değiştir' }}
                </app-button>
              </div>
            </form>
          </div>

          <!-- Tab 3: Satıcı Paneli / Başvuru -->
          <div *ngIf="activeTab === 'seller'" class="space-y-6">
            <h3 class="text-lg font-bold text-zinc-950 dark:text-white uppercase tracking-wide border-b border-zinc-950/5 dark:border-white/5 pb-2.5 flex items-center gap-2">
              <svg lucideStore class="w-5 h-5 text-zinc-400"></svg> Satıcı Durumu
            </h3>

            <!-- User is already a Seller -->
            <div *ngIf="authService.user?.role === 'Seller'; else notSeller" class="space-y-4 text-center py-8">
              <div class="w-12 h-12 bg-emerald-50 dark:bg-emerald-950/20 text-emerald-600 rounded-full flex items-center justify-center mx-auto mb-2">
                <svg lucideStore class="w-6 h-6"></svg>
              </div>
              <h4 class="text-base font-bold text-zinc-900 dark:text-white uppercase">Satıcı Profiliniz Aktif!</h4>
              <p class="text-xs text-zinc-500 dark:text-zinc-400 max-w-sm mx-auto leading-relaxed">
                Mağazanız onaylanmıştır. Ürünlerinizi listelemek, yeni ürün eklemek ve siparişleri yönetmek için satıcı panelini kullanabilirsiniz.
              </p>
              <a href="/seller">
                <app-button variant="primary">
                  Satıcı Paneline Git
                </app-button>
              </a>
            </div>

            <!-- User is not a Seller -->
            <ng-template #notSeller>
              <div *ngIf="loadingStatus" class="text-center py-10">
                <div class="animate-spin inline-block w-6 h-6 border-2 border-zinc-900 border-t-transparent dark:border-white rounded-full"></div>
              </div>

              <div *ngIf="!loadingStatus && sellerStatus">
                
                <!-- Application exists and Pending -->
                <div *ngIf="sellerStatus.hasApplied && sellerStatus.status === 'Pending'" class="flex gap-4 p-5 rounded-2xl bg-amber-50/50 dark:bg-amber-950/20 text-amber-800 dark:text-amber-300 border border-amber-200 dark:border-amber-900/30 text-xs leading-relaxed text-left">
                  <svg lucideAlertCircle class="w-5 h-5 shrink-0"></svg>
                  <div>
                    <strong class="block text-sm font-semibold uppercase mb-1">Başvurunuz Değerlendiriliyor</strong>
                    <strong>Mağaza Adı:</strong> {{ sellerStatus.storeName }} <br />
                    <strong>Destek Hattı:</strong> {{ sellerStatus.supportLine }} <br />
                    <strong>Vergi Dairesi/No:</strong> {{ sellerStatus.taxOffice }} / {{ sellerStatus.taxNumber }} <br />
                    <p class="mt-2 text-zinc-500 dark:text-zinc-400">Başvurunuz admin ekibi tarafından incelenmektedir. Onaylandıktan sonra otomatik olarak satıcı paneline erişiminiz açılacaktır.</p>
                  </div>
                </div>

                <!-- Application exists and Rejected -->
                <div *ngIf="sellerStatus.hasApplied && sellerStatus.status === 'Rejected'" class="space-y-6">
                  <div class="flex gap-4 p-5 rounded-2xl bg-red-50/50 dark:bg-red-950/20 text-red-800 dark:text-red-300 border border-red-200 dark:border-red-900/30 text-xs leading-relaxed text-left">
                    <svg lucideShieldAlert class="w-5 h-5 shrink-0"></svg>
                    <div>
                      <strong class="block text-sm font-semibold uppercase mb-1">Başvurunuz Reddedildi</strong>
                      Maalesef satıcı başvurunuz inceleme sonucunda reddedilmiştir. Bilgilerinizi kontrol ederek tekrar başvuru yapabilirsiniz.
                    </div>
                  </div>

                  <!-- Render Form again to retry -->
                  <ng-container *ngTemplateOutlet="sellerApplyForm"></ng-container>
                </div>

                <!-- No application yet -->
                <div *ngIf="!sellerStatus.hasApplied">
                  <ng-container *ngTemplateOutlet="sellerApplyForm"></ng-container>
                </div>

              </div>
            </ng-template>

            <!-- Reusable Apply Form Template -->
            <ng-template #sellerApplyForm>
              <form (ngSubmit)="onBecomeSeller()" class="space-y-4 text-left">
                <div class="p-4 rounded-xl bg-zinc-950/5 dark:bg-white/5 border border-zinc-950/5 dark:border-white/10 text-xs flex gap-2.5 text-zinc-500">
                  <svg lucideFileText class="w-5 h-5 shrink-0 text-zinc-400"></svg>
                  <p class="leading-relaxed">
                    Siren Store platformunda kendi mağazanızı açarak ürünlerinizi satabilirsiniz. Başvurunuz onaylandığında profiliniz otomatik olarak <strong>Satıcı</strong> rolüne yükseltilecektir.
                  </p>
                </div>

                <app-input
                  label="Mağaza / Dükkan Adı"
                  placeholder="Örn: Siren Butik"
                  [(ngModel)]="sellerData.storeName"
                  name="storeName"
                  [error]="sellerErrors.storeName"
                ></app-input>

                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <app-input
                    label="İletişim E-postası"
                    placeholder="shop@siren.com"
                    [(ngModel)]="sellerData.contactEmail"
                    name="contactEmail"
                    [error]="sellerErrors.contactEmail"
                  ></app-input>
                  <app-input
                    label="İletişim Telefonu"
                    placeholder="5xxxxxxxxx"
                    [(ngModel)]="sellerData.contactPhone"
                    name="contactPhone"
                    [error]="sellerErrors.contactPhone"
                  ></app-input>
                </div>

                <app-input
                  label="Müşteri Destek Hattı"
                  placeholder="E-posta Adresi veya Telefon Numarası"
                  [(ngModel)]="sellerData.supportLine"
                  name="supportLine"
                  [error]="sellerErrors.supportLine"
                ></app-input>

                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <app-input
                    label="Vergi Numarası"
                    placeholder="10 Haneli"
                    [(ngModel)]="sellerData.taxNumber"
                    name="taxNumber"
                    [error]="sellerErrors.taxNumber"
                  ></app-input>
                  <app-input
                    label="Vergi Dairesi"
                    placeholder="Vergi Dairesi Adı"
                    [(ngModel)]="sellerData.taxOffice"
                    name="taxOffice"
                    [error]="sellerErrors.taxOffice"
                  ></app-input>
                </div>

                <div class="pt-4">
                  <app-button type="submit" variant="primary" [disabled]="isLoading">
                    {{ isLoading ? 'Gönderiliyor...' : 'Satıcı Başvurusunu Gönder' }}
                  </app-button>
                </div>
              </form>
            </ng-template>

          </div>

          <!-- Tab 4: Değerlendirmelerim -->
          <div *ngIf="activeTab === 'comments'" class="space-y-6">
            <h3 class="text-lg font-bold text-zinc-950 dark:text-white uppercase tracking-wide border-b border-zinc-950/5 dark:border-white/5 pb-2.5 flex items-center gap-2">
              <svg lucideMessageSquare class="w-5 h-5 text-zinc-400"></svg> Değerlendirmelerim
            </h3>

            <!-- Loading Spinner -->
            <div *ngIf="loadingComments" class="text-center py-10">
              <div class="animate-spin inline-block w-6 h-6 border-2 border-zinc-900 border-t-transparent dark:border-white rounded-full"></div>
            </div>

            <div *ngIf="!loadingComments">
              <!-- Empty State -->
              <div *ngIf="myComments.length === 0" class="text-center py-12 space-y-3">
                <div class="w-12 h-12 bg-zinc-950/5 dark:bg-white/5 text-zinc-400 rounded-full flex items-center justify-center mx-auto">
                  <svg lucideMessageSquare class="w-5 h-5"></svg>
                </div>
                <h4 class="text-sm font-semibold text-zinc-900 dark:text-white">Henüz Değerlendirme Yapmadınız</h4>
                <p class="text-xs text-zinc-500 dark:text-zinc-400 max-w-xs mx-auto leading-relaxed">
                  Satın aldığınız veya incelediğiniz ürünlere yorum yaparak diğer kullanıcılarla paylaşabilirsiniz.
                </p>
              </div>

              <!-- Comments List -->
              <div *ngIf="myComments.length > 0" class="space-y-4">
                <div *ngFor="let comment of paginatedComments" class="flex gap-4 p-5 rounded-2xl bg-zinc-950/[0.01] dark:bg-white/[0.02] border border-zinc-950/5 dark:border-white/10 text-left">
                  <!-- Product Image -->
                  <a [routerLink]="'/product/' + comment.productId" class="shrink-0">
                    <img 
                      *ngIf="comment.productImageUrl" 
                      [src]="comment.productImageUrl" 
                      [alt]="comment.productName"
                      class="w-16 h-16 object-cover rounded-xl border border-zinc-950/5 dark:border-white/5 bg-zinc-100 dark:bg-zinc-800"
                    />
                    <div *ngIf="!comment.productImageUrl" class="w-16 h-16 bg-zinc-100 dark:bg-zinc-800 border border-zinc-950/5 dark:border-white/5 rounded-xl flex items-center justify-center text-zinc-400">
                      <svg lucideExternalLink class="w-5 h-5"></svg>
                    </div>
                  </a>

                  <!-- Details -->
                  <div class="flex-grow space-y-1">
                    <div class="flex items-start justify-between gap-4">
                      <div>
                        <a [routerLink]="'/product/' + comment.productId" class="text-sm font-bold text-zinc-950 dark:text-white hover:underline line-clamp-1">
                          {{ comment.productName }}
                        </a>
                        <!-- Rating stars -->
                        <div class="flex items-center gap-0.5 mt-0.5">
                          <svg 
                            *ngFor="let star of [1,2,3,4,5]" 
                            lucideStar
                            class="w-3.5 h-3.5" 
                            [attr.fill]="star <= comment.rating ? 'currentColor' : 'none'" 
                            [class]="star <= comment.rating ? 'text-amber-500' : 'text-zinc-300 dark:text-zinc-650'"
                          ></svg>
                        </div>
                      </div>
                      
                      <!-- Delete Action -->
                      <button 
                        (click)="onDeleteComment(comment.id)"
                        class="text-zinc-400 hover:text-red-500 transition-colors p-1.5 rounded-lg hover:bg-red-500/10 flex items-center justify-center"
                        title="Değerlendirmeyi Sil"
                      >
                        <svg lucideTrash2 class="w-4 h-4"></svg>
                      </button>
                    </div>

                    <p class="text-xs text-zinc-600 dark:text-zinc-300 leading-relaxed pt-1.5 whitespace-pre-line">
                      {{ comment.text }}
                    </p>

                    <div class="text-[10px] text-zinc-400 dark:text-zinc-500 pt-1 flex items-center gap-1.5">
                      <svg lucideCalendar class="w-3 h-3"></svg>
                      {{ comment.creationDate | date:'dd.MM.yyyy HH:mm' }}
                    </div>
                  </div>
                </div>
                <app-pagination
                  [currentPage]="commentsPage"
                  [totalItems]="myComments.length"
                  [pageSize]="9"
                  (pageChange)="commentsPage = $event"
                ></app-pagination>
              </div>
            </div>
          </div>

        </main>
      </div>

    </div>
  `
})
export class AccountComponent implements OnInit {
  activeTab: 'profile' | 'password' | 'seller' | 'comments' = 'profile';
  isLoading = false;
  loadingStatus = false;
  loadingComments = false;
  myComments: CommentDto[] = [];
  commentsPage = 1;

  get paginatedComments(): CommentDto[] {
    return this.myComments.slice((this.commentsPage - 1) * 9, this.commentsPage * 9);
  }

  // Profile data
  profileData = {
    firstName: '',
    lastName: '',
    phoneNumber: ''
  };
  profileEmail = '';
  profileErrors = {
    firstName: '',
    lastName: '',
    phoneNumber: ''
  };

  // Password data
  passwordData = {
    currentPassword: '',
    newPassword: '',
    confirmNewPassword: ''
  };
  passwordErrors = {
    currentPassword: '',
    newPassword: '',
    confirmNewPassword: ''
  };

  // Seller application data
  sellerData = {
    storeName: '',
    contactEmail: '',
    contactPhone: '',
    supportLine: '',
    taxNumber: '',
    taxOffice: ''
  };
  sellerErrors = {
    storeName: '',
    contactEmail: '',
    contactPhone: '',
    supportLine: '',
    taxNumber: '',
    taxOffice: ''
  };
  sellerStatus: any = null;

  constructor(
    public authService: AuthService,
    private customerService: CustomerService,
    private sellerService: SellerService,
    private toastService: ToastService,
    private commentService: CommentService
  ) { }

  ngOnInit() {
    this.authService.profile$.subscribe(prof => {
      if (prof) {
        this.profileData.firstName = prof.firstName;
        this.profileData.lastName = prof.lastName;
        this.profileData.phoneNumber = prof.phoneNumber || '';
        this.profileEmail = prof.email;
      }
    });

    if (this.authService.user?.role !== 'Seller') {
      this.fetchSellerStatus();
    }
  }

  setActiveTab(tab: 'profile' | 'password' | 'seller' | 'comments') {
    this.activeTab = tab;
    if (tab === 'seller' && this.authService.user?.role !== 'Seller') {
      this.fetchSellerStatus();
    } else if (tab === 'comments') {
      this.fetchMyComments();
    }
  }

  async fetchMyComments() {
    this.loadingComments = true;
    try {
      this.myComments = await this.commentService.getMyComments();
      this.commentsPage = Math.min(this.commentsPage, Math.ceil(this.myComments.length / 9) || 1);
    } catch (err: any) {
      this.toastService.showToast('Değerlendirmeleriniz yüklenemedi.', 'error');
      console.error(err);
    } finally {
      this.loadingComments = false;
    }
  }

  async onDeleteComment(commentId: number) {
    if (!confirm('Bu değerlendirmeyi silmek istediğinize emin misiniz?')) {
      return;
    }
    try {
      await this.commentService.delete(commentId);
      this.toastService.showToast('Değerlendirmeniz silindi.', 'success');
      await this.fetchMyComments();
    } catch (err: any) {
      this.toastService.showToast('Değerlendirme silinemedi.', 'error');
      console.error(err);
    }
  }

  async fetchSellerStatus() {
    this.loadingStatus = true;
    try {
      this.sellerStatus = await this.sellerService.getMyStatus();
    } catch (err) {
      console.error('Failed to get seller status', err);
    } finally {
      this.loadingStatus = false;
    }
  }

  // Update Profile Form submission
  async onUpdateProfile() {
    this.profileErrors.firstName = '';
    this.profileErrors.lastName = '';
    this.profileErrors.phoneNumber = '';

    let isValid = true;
    if (!this.profileData.firstName) {
      this.profileErrors.firstName = 'Ad alanı zorunludur.';
      isValid = false;
    }
    if (!this.profileData.lastName) {
      this.profileErrors.lastName = 'Soyad alanı zorunludur.';
      isValid = false;
    }
    if (!this.profileData.phoneNumber) {
      this.profileErrors.phoneNumber = 'Telefon numarası zorunludur.';
      isValid = false;
    } else if (!/^5\d{9}$/.test(this.profileData.phoneNumber)) {
      this.profileErrors.phoneNumber = 'Telefon numaranız 5 ile başlayan 10 haneli olmalıdır.';
      isValid = false;
    }

    if (!isValid) return;

    this.isLoading = true;
    try {
      await this.customerService.updateProfile({
        firstName: this.profileData.firstName,
        lastName: this.profileData.lastName,
        phoneNumber: this.profileData.phoneNumber || null
      });
      await this.authService.refreshProfile();
      this.toastService.showToast('Profil bilgileriniz başarıyla güncellendi.', 'success');
    } catch (err: any) {
      this.toastService.showToast(err.message || 'Profil güncellenemedi.', 'error');
    } finally {
      this.isLoading = false;
    }
  }

  // Change Password Form submission
  async onChangePassword() {
    this.passwordErrors.currentPassword = '';
    this.passwordErrors.newPassword = '';
    this.passwordErrors.confirmNewPassword = '';

    let isValid = true;
    if (!this.passwordData.currentPassword) {
      this.passwordErrors.currentPassword = 'Mevcut şifreniz zorunludur.';
      isValid = false;
    }
    if (!this.passwordData.newPassword) {
      this.passwordErrors.newPassword = 'Yeni şifreniz zorunludur.';
      isValid = false;
    } else if (this.passwordData.newPassword.length < 6) {
      this.passwordErrors.newPassword = 'Şifre en az 6 karakter olmalıdır.';
      isValid = false;
    }
    if (!this.passwordData.confirmNewPassword) {
      this.passwordErrors.confirmNewPassword = 'Şifre doğrulaması zorunludur.';
      isValid = false;
    } else if (this.passwordData.confirmNewPassword !== this.passwordData.newPassword) {
      this.passwordErrors.confirmNewPassword = 'Şifreler eşleşmiyor!';
      isValid = false;
    }

    if (!isValid) return;

    this.isLoading = true;
    try {
      await this.customerService.changePassword(this.passwordData);
      this.toastService.showToast('Şifreniz başarıyla değiştirildi.', 'success');
      this.passwordData = { currentPassword: '', newPassword: '', confirmNewPassword: '' };
    } catch (err: any) {
      this.toastService.showToast(err.message || 'Şifre değiştirilemedi.', 'error');
    } finally {
      this.isLoading = false;
    }
  }

  // Become Seller Form submission
  async onBecomeSeller() {
    this.sellerErrors.storeName = '';
    this.sellerErrors.contactEmail = '';
    this.sellerErrors.contactPhone = '';
    this.sellerErrors.supportLine = '';
    this.sellerErrors.taxNumber = '';
    this.sellerErrors.taxOffice = '';

    let isValid = true;
    if (!this.sellerData.storeName) {
      this.sellerErrors.storeName = 'Mağaza adı zorunludur.';
      isValid = false;
    }
    if (!this.sellerData.contactEmail) {
      this.sellerErrors.contactEmail = 'İletişim maili zorunludur.';
      isValid = false;
    }
    if (!this.sellerData.contactPhone) {
      this.sellerErrors.contactPhone = 'Telefon zorunludur.';
      isValid = false;
    }
    if (!this.sellerData.supportLine) {
      this.sellerErrors.supportLine = 'Müşteri destek hattı zorunludur.';
      isValid = false;
    }
    if (!this.sellerData.taxNumber) {
      this.sellerErrors.taxNumber = 'Vergi no zorunludur.';
      isValid = false;
    }
    if (!this.sellerData.taxOffice) {
      this.sellerErrors.taxOffice = 'Vergi dairesi zorunludur.';
      isValid = false;
    }

    if (!isValid) return;

    this.isLoading = true;
    try {
      await this.sellerService.becomeSeller(this.sellerData);
      this.toastService.showToast('Satıcı başvurunuz başarıyla alındı. Admin onayı bekleniyor.', 'success');
      await this.fetchSellerStatus();
      this.sellerData = { storeName: '', contactEmail: '', contactPhone: '', supportLine: '', taxNumber: '', taxOffice: '' };
    } catch (err: any) {
      this.toastService.showToast(err.message || 'Satıcı başvurusu tamamlanamadı.', 'error');
    } finally {
      this.isLoading = false;
    }
  }
}

// Frontend/src/pages/Account/index.tsx
import React, { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { useAuth } from '../../hooks/useAuth';
import { customerService } from '../../services/customerService';
import { sellerService } from '../../services/sellerService';
import { useToast } from '../../context/ToastContext';
import { Input } from '../../components/Input';
import { Button } from '../../components/Button';
import { User, Key, Store, ClipboardList, Info, ShieldAlert } from 'lucide-react';

export const Account: React.FC = () => {
  const { user, profile, refreshProfile } = useAuth();
  const { showToast } = useToast();
  
  const [activeTab, setActiveTab] = useState<'profile' | 'password' | 'seller'>('profile');
  const [isLoading, setIsLoading] = useState(false);

  // Seller application status
  const [sellerStatus, setSellerStatus] = useState<any>(null);
  const [loadingStatus, setLoadingStatus] = useState(false);

  const fetchSellerStatus = async () => {
    if (!user) return;
    setLoadingStatus(true);
    try {
      const data = await sellerService.getMyStatus();
      setSellerStatus(data);
    } catch (err: any) {
      console.error('Failed to get seller status', err);
    } finally {
      setLoadingStatus(false);
    }
  };

  useEffect(() => {
    if (activeTab === 'seller' && user?.role !== 'Seller') {
      fetchSellerStatus();
    }
  }, [activeTab, user]);

  // Form hooks
  const profileForm = useForm({
    defaultValues: {
      firstName: profile?.firstName || '',
      lastName: profile?.lastName || '',
      phoneNumber: profile?.phoneNumber || '',
    },
  });

  const passwordForm = useForm({
    defaultValues: {
      currentPassword: '',
      newPassword: '',
      confirmNewPassword: '',
    },
  });

  const sellerForm = useForm({
    defaultValues: {
      storeName: '',
      contactEmail: '',
      contactPhone: '',
      supportLine: '',
      taxNumber: '',
      taxOffice: '',
    },
  });

  // Sync profile details when loaded
  useEffect(() => {
    if (profile) {
      profileForm.reset({
        firstName: profile.firstName,
        lastName: profile.lastName,
        phoneNumber: profile.phoneNumber || '',
      });
    }
  }, [profile]);

  const onUpdateProfile = async (data: any) => {
    setIsLoading(true);
    try {
      await customerService.updateProfile({
        firstName: data.firstName,
        lastName: data.lastName,
        phoneNumber: data.phoneNumber || null,
      });
      await refreshProfile();
      showToast('Profil bilgileriniz başarıyla güncellendi.', 'success');
    } catch (err: any) {
      showToast(err.message || 'Profil güncellenemedi.', 'error');
    } finally {
      setIsLoading(false);
    }
  };

  const onChangePassword = async (data: any) => {
    setIsLoading(true);
    try {
      await customerService.changePassword(data);
      showToast('Şifreniz başarıyla değiştirildi.', 'success');
      passwordForm.reset();
    } catch (err: any) {
      showToast(err.message || 'Şifre değiştirilemedi.', 'error');
    } finally {
      setIsLoading(false);
    }
  };

  const onBecomeSeller = async (data: any) => {
    setIsLoading(true);
    try {
      await sellerService.becomeSeller(data);
      showToast('Satıcı başvurunuz başarıyla alındı. Admin onayı bekleniyor.', 'success');
      await fetchSellerStatus();
      sellerForm.reset();
    } catch (err: any) {
      showToast(err.message || 'Satıcı başvurusu tamamlanamadı.', 'error');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto px-6 py-10 space-y-8 text-left">
      
      {/* Header */}
      <div className="border-b border-zinc-950/5 dark:border-white/5 pb-6">
        <h1 className="text-4xl font-extrabold tracking-tight text-zinc-950 dark:text-white uppercase leading-none">
          Hesabım
        </h1>
        <p className="text-sm text-zinc-500 dark:text-zinc-400 mt-1.5">
          Kişisel bilgilerinizi, şifrenizi yönetin ve mağaza başvurularınızı inceleyin.
        </p>
      </div>

      {/* Tabs Layout */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
        
        {/* Sidebar Navigation */}
        <nav className="md:col-span-1 flex flex-col gap-2">
          <button
            onClick={() => setActiveTab('profile')}
            className={`flex items-center gap-2.5 px-4 py-3 rounded-xl text-sm font-semibold text-left transition-all ${
              activeTab === 'profile'
                ? 'bg-zinc-950 text-white dark:bg-white dark:text-zinc-950 shadow-md'
                : 'text-zinc-600 dark:text-zinc-400 hover:bg-zinc-950/5 dark:hover:bg-white/5'
            }`}
          >
            <User className="w-4 h-4" /> Profilim
          </button>
          
          <button
            onClick={() => setActiveTab('password')}
            className={`flex items-center gap-2.5 px-4 py-3 rounded-xl text-sm font-semibold text-left transition-all ${
              activeTab === 'password'
                ? 'bg-zinc-950 text-white dark:bg-white dark:text-zinc-950 shadow-md'
                : 'text-zinc-600 dark:text-zinc-400 hover:bg-zinc-950/5 dark:hover:bg-white/5'
            }`}
          >
            <Key className="w-4 h-4" /> Şifre Değiştir
          </button>
          
          <button
            onClick={() => setActiveTab('seller')}
            className={`flex items-center gap-2.5 px-4 py-3 rounded-xl text-sm font-semibold text-left transition-all ${
              activeTab === 'seller'
                ? 'bg-zinc-950 text-white dark:bg-white dark:text-zinc-950 shadow-md'
                : 'text-zinc-600 dark:text-zinc-400 hover:bg-zinc-950/5 dark:hover:bg-white/5'
            }`}
          >
            <Store className="w-4 h-4" /> Satıcı Paneli / Başvuru
          </button>
        </nav>

        {/* Tab Contents */}
        <main className="md:col-span-3 glass-surface bg-zinc-950/[0.01] dark:bg-white/5 border border-zinc-950/5 dark:border-white/10 p-8 rounded-3xl">
          
          {/* Tab 1: Profilim */}
          {activeTab === 'profile' && (
            <form onSubmit={profileForm.handleSubmit(onUpdateProfile)} className="space-y-6">
              <h3 className="text-lg font-bold text-zinc-950 dark:text-white uppercase tracking-wide border-b border-zinc-950/5 dark:border-white/5 pb-2.5 flex items-center gap-2">
                <User className="w-5 h-5 text-zinc-400" /> Profil Bilgileri
              </h3>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <Input
                  label="Ad"
                  placeholder="Adınız"
                  error={profileForm.formState.errors.firstName?.message}
                  {...profileForm.register('firstName', { required: 'Ad alanı zorunludur.' })}
                />
                <Input
                  label="Soyad"
                  placeholder="Soyadınız"
                  error={profileForm.formState.errors.lastName?.message}
                  {...profileForm.register('lastName', { required: 'Soyad alanı zorunludur.' })}
                />
              </div>

              <Input
                label="E-posta Adresi (Değiştirilemez)"
                type="email"
                disabled
                value={profile?.email || ''}
                className="opacity-60 cursor-not-allowed bg-zinc-950/5 dark:bg-white/5"
              />

              <Input
                label="Telefon Numarası"
                placeholder="5xxxxxxxxx"
                error={profileForm.formState.errors.phoneNumber?.message}
                {...profileForm.register('phoneNumber', {
                  required: 'Telefon numarası zorunludur.',
                  pattern: {
                    value: /^5\d{9}$/,
                    message: 'Telefon numaranız 5 ile başlayan 10 haneli olmalıdır (Örn: 5XXXXXXXXX).',
                  },
                })}
              />

              <Button type="submit" variant="primary" disabled={isLoading}>
                {isLoading ? 'Güncelleniyor...' : 'Profilimi Güncelle'}
              </Button>
            </form>
          )}

          {/* Tab 2: Şifre Değiştir */}
          {activeTab === 'password' && (
            <form onSubmit={passwordForm.handleSubmit(onChangePassword)} className="space-y-6">
              <h3 className="text-lg font-bold text-zinc-950 dark:text-white uppercase tracking-wide border-b border-zinc-950/5 dark:border-white/5 pb-2.5 flex items-center gap-2">
                <Key className="w-5 h-5 text-zinc-400" /> Güvenlik & Şifre
              </h3>

              <Input
                label="Mevcut Şifre"
                type="password"
                placeholder="••••••••"
                error={passwordForm.formState.errors.currentPassword?.message}
                {...passwordForm.register('currentPassword', { required: 'Mevcut şifreniz zorunludur.' })}
              />

              <Input
                label="Yeni Şifre"
                type="password"
                placeholder="••••••••"
                error={passwordForm.formState.errors.newPassword?.message}
                {...passwordForm.register('newPassword', { 
                  required: 'Yeni şifreniz zorunludur.',
                  minLength: { value: 6, message: 'Şifre en az 6 karakter olmalıdır.' }
                })}
              />

              <Input
                label="Yeni Şifre Tekrar"
                type="password"
                placeholder="••••••••"
                error={passwordForm.formState.errors.confirmNewPassword?.message}
                {...passwordForm.register('confirmNewPassword', { 
                  required: 'Şifre doğrulaması zorunludur.',
                  validate: (value) => value === passwordForm.getValues('newPassword') || 'Şifreler eşleşmiyor!'
                })}
              />

              <Button type="submit" variant="primary" disabled={isLoading}>
                {isLoading ? 'Değiştiriliyor...' : 'Şifreyi Değiştir'}
              </Button>
            </form>
          )}

          {/* Tab 3: Satıcı Paneli / Başvuru */}
          {activeTab === 'seller' && (
            <div className="space-y-6">
              <h3 className="text-lg font-bold text-zinc-950 dark:text-white uppercase tracking-wide border-b border-zinc-950/5 dark:border-white/5 pb-2.5 flex items-center gap-2">
                <Store className="w-5 h-5 text-zinc-400" /> Satıcı Durumu
              </h3>

              {user?.role === 'Seller' ? (
                /* User is already a Seller */
                <div className="space-y-4 text-center py-8">
                  <div className="w-12 h-12 bg-emerald-50 dark:bg-emerald-950/20 text-emerald-600 rounded-full flex items-center justify-center mx-auto mb-2">
                    <Store className="w-6 h-6" />
                  </div>
                  <h4 className="text-base font-bold text-zinc-900 dark:text-white uppercase">Satıcı Profiliniz Aktif!</h4>
                  <p className="text-xs text-zinc-500 dark:text-zinc-400 max-w-sm mx-auto leading-relaxed">
                    Mağazanız onaylanmıştır. Ürünlerinizi listelemek, yeni ürün eklemek ve siparişleri yönetmek için satıcı panelini kullanabilirsiniz.
                  </p>
                  <Button variant="primary" onClick={() => (window.location.href = '/seller')}>
                    Satıcı Paneline Git
                  </Button>
                </div>
              ) : loadingStatus ? (
                <div className="text-center py-10">
                  <div className="animate-spin inline-block w-6 h-6 border-2 border-zinc-900 border-t-transparent dark:border-white rounded-full" />
                </div>
              ) : sellerStatus?.hasApplied ? (
                /* Application exists */
                sellerStatus.status === 'Pending' ? (
                  <div className="flex gap-4 p-5 rounded-2xl bg-amber-50/50 dark:bg-amber-950/20 text-amber-800 dark:text-amber-300 border border-amber-200 dark:border-amber-900/30 text-xs leading-relaxed">
                    <Info className="w-5 h-5 shrink-0" />
                    <div>
                      <strong className="block text-sm font-semibold uppercase mb-1">Başvurunuz Değerlendiriliyor</strong>
                      <strong>Mağaza Adı:</strong> {sellerStatus.storeName} <br />
                      <strong>Destek Hattı:</strong> {sellerStatus.supportLine} <br />
                      <strong>Vergi Dairesi/No:</strong> {sellerStatus.taxOffice} / {sellerStatus.taxNumber} <br />
                      <p className="mt-2 text-zinc-500 dark:text-zinc-400">Başvurunuz admin ekibi tarafından incelenmektedir. Onaylandıktan sonra otomatik olarak satıcı paneline erişiminiz açılacaktır.</p>
                    </div>
                  </div>
                ) : sellerStatus.status === 'Rejected' ? (
                  <div className="space-y-6">
                    <div className="flex gap-4 p-5 rounded-2xl bg-red-50/50 dark:bg-red-950/20 text-red-800 dark:text-red-300 border border-red-200 dark:border-red-900/30 text-xs leading-relaxed">
                      <ShieldAlert className="w-5 h-5 shrink-0" />
                      <div>
                        <strong className="block text-sm font-semibold uppercase mb-1">Başvurunuz Reddedildi</strong>
                        Maalesef satıcı başvurunuz inceleme sonucunda reddedilmiştir. Bilgilerinizi kontrol ederek tekrar başvuru yapabilirsiniz.
                      </div>
                    </div>

                    <form onSubmit={sellerForm.handleSubmit(onBecomeSeller)} className="space-y-4 text-left">
                      <h4 className="text-sm font-bold uppercase tracking-wider text-zinc-400">Yeni Satıcı Başvurusu</h4>
                      
                      <Input
                        label="Mağaza / Dükkan Adı"
                        placeholder="Örn: Siren Butik"
                        error={sellerForm.formState.errors.storeName?.message}
                        {...sellerForm.register('storeName', { required: 'Mağaza adı zorunludur.' })}
                      />
                      
                      <div className="grid grid-cols-2 gap-4">
                        <Input
                          label="İletişim E-postası"
                          placeholder="shop@siren.com"
                          error={sellerForm.formState.errors.contactEmail?.message}
                          {...sellerForm.register('contactEmail', { required: 'İletişim maili zorunludur.' })}
                        />
                        <Input
                          label="İletişim Telefonu"
                          placeholder="5xxxxxxxxx"
                          error={sellerForm.formState.errors.contactPhone?.message}
                          {...sellerForm.register('contactPhone', { required: 'Telefon zorunludur.' })}
                        />
                      </div>

                      <Input
                        label="Müşteri Destek Hattı"
                        placeholder="0850xxxxxxx veya 0212xxxxxxx"
                        error={sellerForm.formState.errors.supportLine?.message}
                        {...sellerForm.register('supportLine', { required: 'Müşteri destek hattı zorunludur.' })}
                      />

                      <div className="grid grid-cols-2 gap-4">
                        <Input
                          label="Vergi Numarası"
                          placeholder="10 Haneli"
                          error={sellerForm.formState.errors.taxNumber?.message}
                          {...sellerForm.register('taxNumber', { required: 'Vergi no zorunludur.' })}
                        />
                        <Input
                          label="Vergi Dairesi"
                          placeholder="Vergi Dairesi Adı"
                          error={sellerForm.formState.errors.taxOffice?.message}
                          {...sellerForm.register('taxOffice', { required: 'Vergi dairesi zorunludur.' })}
                        />
                      </div>

                      <Button type="submit" variant="primary" disabled={isLoading}>
                        {isLoading ? 'Gönderiliyor...' : 'Satıcı Başvurusunu Gönder'}
                      </Button>
                    </form>
                  </div>
                ) : null
              ) : (
                /* No application yet - Render application form */
                <form onSubmit={sellerForm.handleSubmit(onBecomeSeller)} className="space-y-4 text-left">
                  <div className="p-4 rounded-xl bg-zinc-950/5 dark:bg-white/5 border border-zinc-950/5 dark:border-white/10 text-xs flex gap-2.5 text-zinc-500">
                    <ClipboardList className="w-5 h-5 shrink-0 text-zinc-400" />
                    <p className="leading-relaxed">
                      Siren Store platformunda kendi mağazanızı açarak ürünlerinizi satabilirsiniz. Başvurunuz onaylandığında profiliniz otomatik olarak <strong>Satıcı</strong> rolüne yükseltilecektir.
                    </p>
                  </div>

                  <Input
                    label="Mağaza / Dükkan Adı"
                    placeholder="Örn: Siren Butik"
                    error={sellerForm.formState.errors.storeName?.message}
                    {...sellerForm.register('storeName', { required: 'Mağaza adı zorunludur.' })}
                  />

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <Input
                      label="İletişim E-postası"
                      placeholder="shop@siren.com"
                      error={sellerForm.formState.errors.contactEmail?.message}
                      {...sellerForm.register('contactEmail', { required: 'İletişim maili zorunludur.' })}
                    />
                    <Input
                      label="İletişim Telefonu"
                      placeholder="5xxxxxxxxx"
                      error={sellerForm.formState.errors.contactPhone?.message}
                      {...sellerForm.register('contactPhone', { required: 'Telefon zorunludur.' })}
                    />
                  </div>

                  <Input
                    label="Müşteri Destek Hattı"
                    placeholder="0850xxxxxxx veya 0212xxxxxxx"
                    error={sellerForm.formState.errors.supportLine?.message}
                    {...sellerForm.register('supportLine', { required: 'Müşteri destek hattı zorunludur.' })}
                  />

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <Input
                      label="Vergi Numarası"
                      placeholder="10 Haneli"
                      error={sellerForm.formState.errors.taxNumber?.message}
                      {...sellerForm.register('taxNumber', { required: 'Vergi no zorunludur.' })}
                    />
                    <Input
                      label="Vergi Dairesi"
                      placeholder="Vergi Dairesi Adı"
                      error={sellerForm.formState.errors.taxOffice?.message}
                      {...sellerForm.register('taxOffice', { required: 'Vergi dairesi zorunludur.' })}
                    />
                  </div>

                  <Button type="submit" variant="primary" disabled={isLoading} className="mt-2">
                    {isLoading ? 'Gönderiliyor...' : 'Satıcı Başvurusunu Gönder'}
                  </Button>
                </form>
              )}

            </div>
          )}

        </main>
      </div>

    </div>
  );
};
